apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: recommendation-cpu-stress
  namespace: default
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: recommendationservice
  stressors:
    cpu:
      workers: 2
      load: 90
  duration: '120s'
